# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui/delete_key_pair.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DeleteKeyPairDialog(object):
    def setupUi(self, DeleteKeyPairDialog):
        DeleteKeyPairDialog.setObjectName("DeleteKeyPairDialog")
        DeleteKeyPairDialog.resize(450, 218)
        self.buttonBox = QtWidgets.QDialogButtonBox(DeleteKeyPairDialog)
        self.buttonBox.setGeometry(QtCore.QRect(70, 150, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtWidgets.QLabel(DeleteKeyPairDialog)
        self.label.setGeometry(QtCore.QRect(130, 40, 191, 31))
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.comboBox = QtWidgets.QComboBox(DeleteKeyPairDialog)
        self.comboBox.setGeometry(QtCore.QRect(80, 90, 291, 21))
        self.comboBox.setObjectName("comboBox")

        self.retranslateUi(DeleteKeyPairDialog)
        self.buttonBox.accepted.connect(DeleteKeyPairDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(DeleteKeyPairDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(DeleteKeyPairDialog)

    def retranslateUi(self, DeleteKeyPairDialog):
        _translate = QtCore.QCoreApplication.translate
        DeleteKeyPairDialog.setWindowTitle(_translate("DeleteKeyPairDialog", "Delete Key Pair"))
        self.label.setText(_translate("DeleteKeyPairDialog", "Select a key pair do delete:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DeleteKeyPairDialog = QtWidgets.QDialog()
    ui = Ui_DeleteKeyPairDialog()
    ui.setupUi(DeleteKeyPairDialog)
    DeleteKeyPairDialog.show()
    sys.exit(app.exec_())
