# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui/export_key.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ExportKeyDialog(object):
    def setupUi(self, ExportKeyDialog):
        ExportKeyDialog.setObjectName("ExportKeyDialog")
        ExportKeyDialog.resize(450, 218)
        self.buttonBox = QtWidgets.QDialogButtonBox(ExportKeyDialog)
        self.buttonBox.setGeometry(QtCore.QRect(70, 150, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.publicRadioButton = QtWidgets.QRadioButton(ExportKeyDialog)
        self.publicRadioButton.setGeometry(QtCore.QRect(171, 110, 111, 20))
        self.publicRadioButton.setChecked(True)
        self.publicRadioButton.setObjectName("publicRadioButton")
        self.label = QtWidgets.QLabel(ExportKeyDialog)
        self.label.setGeometry(QtCore.QRect(130, 30, 191, 31))
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.pairRadioButton = QtWidgets.QRadioButton(ExportKeyDialog)
        self.pairRadioButton.setGeometry(QtCore.QRect(300, 110, 82, 17))
        self.pairRadioButton.setObjectName("pairRadioButton")
        self.comboBox = QtWidgets.QComboBox(ExportKeyDialog)
        self.comboBox.setGeometry(QtCore.QRect(80, 80, 291, 21))
        self.comboBox.setObjectName("comboBox")

        self.retranslateUi(ExportKeyDialog)
        self.buttonBox.accepted.connect(ExportKeyDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(ExportKeyDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(ExportKeyDialog)

    def retranslateUi(self, ExportKeyDialog):
        _translate = QtCore.QCoreApplication.translate
        ExportKeyDialog.setWindowTitle(_translate("ExportKeyDialog", "Export Key"))
        self.publicRadioButton.setText(_translate("ExportKeyDialog", "Only public key"))
        self.label.setText(_translate("ExportKeyDialog", "Choose a key or key pair to export:"))
        self.pairRadioButton.setText(_translate("ExportKeyDialog", "Whole pair"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ExportKeyDialog = QtWidgets.QDialog()
    ui = Ui_ExportKeyDialog()
    ui.setupUi(ExportKeyDialog)
    ExportKeyDialog.show()
    sys.exit(app.exec_())
