# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui/generate_key_pair.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GenerateKeyPairDialog(object):
    def setupUi(self, GenerateKeyPairDialog):
        GenerateKeyPairDialog.setObjectName("GenerateKeyPairDialog")
        GenerateKeyPairDialog.resize(400, 300)
        self.buttonBox = QtWidgets.QDialogButtonBox(GenerateKeyPairDialog)
        self.buttonBox.setGeometry(QtCore.QRect(30, 240, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.nameLineEdit = QtWidgets.QLineEdit(GenerateKeyPairDialog)
        self.nameLineEdit.setGeometry(QtCore.QRect(190, 40, 113, 20))
        self.nameLineEdit.setObjectName("nameLineEdit")
        self.emailLineEdit = QtWidgets.QLineEdit(GenerateKeyPairDialog)
        self.emailLineEdit.setGeometry(QtCore.QRect(190, 90, 113, 20))
        self.emailLineEdit.setObjectName("emailLineEdit")
        self.passLineEdit = QtWidgets.QLineEdit(GenerateKeyPairDialog)
        self.passLineEdit.setGeometry(QtCore.QRect(190, 190, 113, 20))
        self.passLineEdit.setObjectName("passLineEdit")
        self.emailLabel = QtWidgets.QLabel(GenerateKeyPairDialog)
        self.emailLabel.setGeometry(QtCore.QRect(100, 90, 47, 13))
        self.emailLabel.setObjectName("emailLabel")
        self.keySizeLabel = QtWidgets.QLabel(GenerateKeyPairDialog)
        self.keySizeLabel.setGeometry(QtCore.QRect(100, 140, 47, 13))
        self.keySizeLabel.setObjectName("keySizeLabel")
        self.passLabel = QtWidgets.QLabel(GenerateKeyPairDialog)
        self.passLabel.setGeometry(QtCore.QRect(100, 190, 47, 13))
        self.passLabel.setObjectName("passLabel")
        self.nameLabel = QtWidgets.QLabel(GenerateKeyPairDialog)
        self.nameLabel.setGeometry(QtCore.QRect(100, 40, 47, 13))
        self.nameLabel.setObjectName("nameLabel")
        self.comboBox = QtWidgets.QComboBox(GenerateKeyPairDialog)
        self.comboBox.setGeometry(QtCore.QRect(190, 140, 111, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")

        self.retranslateUi(GenerateKeyPairDialog)
        self.buttonBox.accepted.connect(GenerateKeyPairDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(GenerateKeyPairDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(GenerateKeyPairDialog)

    def retranslateUi(self, GenerateKeyPairDialog):
        _translate = QtCore.QCoreApplication.translate
        GenerateKeyPairDialog.setWindowTitle(_translate("GenerateKeyPairDialog", "Generate Key Pair"))
        self.emailLabel.setText(_translate("GenerateKeyPairDialog", "Email:"))
        self.keySizeLabel.setText(_translate("GenerateKeyPairDialog", "Key size:"))
        self.passLabel.setText(_translate("GenerateKeyPairDialog", "Password:"))
        self.nameLabel.setText(_translate("GenerateKeyPairDialog", "Name:"))
        self.comboBox.setItemText(0, _translate("GenerateKeyPairDialog", "1024 bits"))
        self.comboBox.setItemText(1, _translate("GenerateKeyPairDialog", "2048 bits"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    GenerateKeyPairDialog = QtWidgets.QDialog()
    ui = Ui_GenerateKeyPairDialog()
    ui.setupUi(GenerateKeyPairDialog)
    GenerateKeyPairDialog.show()
    sys.exit(app.exec_())
