# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui/import_key.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ImportKeyDialog(object):
    def setupUi(self, ImportKeyDialog):
        ImportKeyDialog.setObjectName("ImportKeyDialog")
        ImportKeyDialog.resize(400, 300)
        self.buttonBox = QtWidgets.QDialogButtonBox(ImportKeyDialog)
        self.buttonBox.setGeometry(QtCore.QRect(30, 240, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.emailLabel = QtWidgets.QLabel(ImportKeyDialog)
        self.emailLabel.setGeometry(QtCore.QRect(100, 110, 47, 13))
        self.emailLabel.setObjectName("emailLabel")
        self.passphraseLabel = QtWidgets.QLabel(ImportKeyDialog)
        self.passphraseLabel.setGeometry(QtCore.QRect(100, 160, 59, 13))
        self.passphraseLabel.setObjectName("passphraseLabel")
        self.nameLabel = QtWidgets.QLabel(ImportKeyDialog)
        self.nameLabel.setGeometry(QtCore.QRect(100, 60, 47, 13))
        self.nameLabel.setObjectName("nameLabel")
        self.nameLineEdit = QtWidgets.QLineEdit(ImportKeyDialog)
        self.nameLineEdit.setGeometry(QtCore.QRect(190, 60, 113, 20))
        self.nameLineEdit.setObjectName("nameLineEdit")
        self.emailLineEdit = QtWidgets.QLineEdit(ImportKeyDialog)
        self.emailLineEdit.setGeometry(QtCore.QRect(190, 110, 113, 20))
        self.emailLineEdit.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.emailLineEdit.setPlaceholderText("")
        self.emailLineEdit.setObjectName("emailLineEdit")
        self.passphraseLineEdit = QtWidgets.QLineEdit(ImportKeyDialog)
        self.passphraseLineEdit.setGeometry(QtCore.QRect(190, 160, 113, 20))
        self.passphraseLineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passphraseLineEdit.setObjectName("passphraseLineEdit")

        self.retranslateUi(ImportKeyDialog)
        self.buttonBox.accepted.connect(ImportKeyDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(ImportKeyDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(ImportKeyDialog)

    def retranslateUi(self, ImportKeyDialog):
        _translate = QtCore.QCoreApplication.translate
        ImportKeyDialog.setWindowTitle(_translate("ImportKeyDialog", "Import Key"))
        self.emailLabel.setText(_translate("ImportKeyDialog", "Email:"))
        self.passphraseLabel.setText(_translate("ImportKeyDialog", "Passphrase:"))
        self.nameLabel.setText(_translate("ImportKeyDialog", "Name:"))
        self.passphraseLineEdit.setPlaceholderText(_translate("ImportKeyDialog", "(If needed)"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ImportKeyDialog = QtWidgets.QDialog()
    ui = Ui_ImportKeyDialog()
    ui.setupUi(ImportKeyDialog)
    ImportKeyDialog.show()
    sys.exit(app.exec_())
