# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui/main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.manageKeysButton = QtWidgets.QPushButton(self.centralwidget)
        self.manageKeysButton.setGeometry(QtCore.QRect(320, 110, 161, 41))
        self.manageKeysButton.setObjectName("manageKeysButton")
        self.sendButton = QtWidgets.QPushButton(self.centralwidget)
        self.sendButton.setGeometry(QtCore.QRect(320, 260, 161, 41))
        self.sendButton.setObjectName("sendButton")
        self.receiveButton = QtWidgets.QPushButton(self.centralwidget)
        self.receiveButton.setGeometry(QtCore.QRect(320, 410, 161, 41))
        self.receiveButton.setObjectName("receiveButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuMessage = QtWidgets.QMenu(self.menuFile)
        self.menuMessage.setObjectName("menuMessage")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionKeys = QtWidgets.QAction(MainWindow)
        self.actionKeys.setObjectName("actionKeys")
        self.actionSend = QtWidgets.QAction(MainWindow)
        self.actionSend.setObjectName("actionSend")
        self.actionReceive = QtWidgets.QAction(MainWindow)
        self.actionReceive.setObjectName("actionReceive")
        self.menuMessage.addAction(self.actionSend)
        self.menuMessage.addAction(self.actionReceive)
        self.menuFile.addAction(self.actionKeys)
        self.menuFile.addAction(self.menuMessage.menuAction())
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PGP"))
        self.manageKeysButton.setText(_translate("MainWindow", "Key Management"))
        self.sendButton.setText(_translate("MainWindow", "Send Message"))
        self.receiveButton.setText(_translate("MainWindow", "Receive Message"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuMessage.setTitle(_translate("MainWindow", "Message"))
        self.actionKeys.setText(_translate("MainWindow", "Keys"))
        self.actionKeys.setShortcut(_translate("MainWindow", "Ctrl+K"))
        self.actionSend.setText(_translate("MainWindow", "Send"))
        self.actionSend.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionReceive.setText(_translate("MainWindow", "Receive"))
        self.actionReceive.setShortcut(_translate("MainWindow", "Ctrl+R"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
