# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui/passphrase.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PassphraseDIalog(object):
    def setupUi(self, PassphraseDIalog):
        PassphraseDIalog.setObjectName("PassphraseDIalog")
        PassphraseDIalog.resize(343, 160)
        self.buttonBox = QtWidgets.QDialogButtonBox(PassphraseDIalog)
        self.buttonBox.setGeometry(QtCore.QRect(10, 110, 301, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.passphraseLabel = QtWidgets.QLabel(PassphraseDIalog)
        self.passphraseLabel.setGeometry(QtCore.QRect(40, 50, 71, 16))
        self.passphraseLabel.setObjectName("passphraseLabel")
        self.lineEdit = QtWidgets.QLineEdit(PassphraseDIalog)
        self.lineEdit.setGeometry(QtCore.QRect(130, 50, 171, 20))
        self.lineEdit.setObjectName("lineEdit")

        self.retranslateUi(PassphraseDIalog)
        self.buttonBox.accepted.connect(PassphraseDIalog.accept) # type: ignore
        self.buttonBox.rejected.connect(PassphraseDIalog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(PassphraseDIalog)

    def retranslateUi(self, PassphraseDIalog):
        _translate = QtCore.QCoreApplication.translate
        PassphraseDIalog.setWindowTitle(_translate("PassphraseDIalog", "Enter passphrase"))
        self.passphraseLabel.setText(_translate("PassphraseDIalog", "Passphrase:"))
        self.lineEdit.setPlaceholderText(_translate("PassphraseDIalog", "(If needed)"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PassphraseDIalog = QtWidgets.QDialog()
    ui = Ui_PassphraseDIalog()
    ui.setupUi(PassphraseDIalog)
    PassphraseDIalog.show()
    sys.exit(app.exec_())
