# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui/receive_message.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ReceiveMessageDialog(object):
    def setupUi(self, ReceiveMessageDialog):
        ReceiveMessageDialog.setObjectName("ReceiveMessageDialog")
        ReceiveMessageDialog.resize(640, 530)
        self.buttonBox = QtWidgets.QDialogButtonBox(ReceiveMessageDialog)
        self.buttonBox.setGeometry(QtCore.QRect(240, 460, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.compressedCheckBox = QtWidgets.QCheckBox(ReceiveMessageDialog)
        self.compressedCheckBox.setGeometry(QtCore.QRect(40, 90, 121, 17))
        self.compressedCheckBox.setCheckable(False)
        self.compressedCheckBox.setObjectName("compressedCheckBox")
        self.encryptedCheckBox = QtWidgets.QCheckBox(ReceiveMessageDialog)
        self.encryptedCheckBox.setGeometry(QtCore.QRect(40, 30, 121, 17))
        self.encryptedCheckBox.setCheckable(False)
        self.encryptedCheckBox.setObjectName("encryptedCheckBox")
        self.signedCheckBox = QtWidgets.QCheckBox(ReceiveMessageDialog)
        self.signedCheckBox.setGeometry(QtCore.QRect(40, 60, 121, 17))
        self.signedCheckBox.setCheckable(False)
        self.signedCheckBox.setObjectName("signedCheckBox")
        self.publicLabel = QtWidgets.QLabel(ReceiveMessageDialog)
        self.publicLabel.setGeometry(QtCore.QRect(340, 110, 131, 16))
        self.publicLabel.setObjectName("publicLabel")
        self.messageText = QtWidgets.QTextEdit(ReceiveMessageDialog)
        self.messageText.setGeometry(QtCore.QRect(40, 200, 561, 231))
        self.messageText.setReadOnly(True)
        self.messageText.setObjectName("messageText")
        self.algorithmLabel = QtWidgets.QLabel(ReceiveMessageDialog)
        self.algorithmLabel.setGeometry(QtCore.QRect(340, 150, 131, 16))
        self.algorithmLabel.setObjectName("algorithmLabel")
        self.convertedCheckBox = QtWidgets.QCheckBox(ReceiveMessageDialog)
        self.convertedCheckBox.setGeometry(QtCore.QRect(40, 120, 121, 17))
        self.convertedCheckBox.setCheckable(False)
        self.convertedCheckBox.setObjectName("convertedCheckBox")
        self.privateLabel = QtWidgets.QLabel(ReceiveMessageDialog)
        self.privateLabel.setGeometry(QtCore.QRect(340, 70, 131, 16))
        self.privateLabel.setObjectName("privateLabel")
        self.messageLabel = QtWidgets.QLabel(ReceiveMessageDialog)
        self.messageLabel.setGeometry(QtCore.QRect(50, 160, 61, 16))
        self.messageLabel.setObjectName("messageLabel")
        self.privateLineEdit = QtWidgets.QLineEdit(ReceiveMessageDialog)
        self.privateLineEdit.setGeometry(QtCore.QRect(480, 70, 121, 20))
        self.privateLineEdit.setReadOnly(True)
        self.privateLineEdit.setObjectName("privateLineEdit")
        self.publicLineEdit = QtWidgets.QLineEdit(ReceiveMessageDialog)
        self.publicLineEdit.setGeometry(QtCore.QRect(480, 110, 121, 20))
        self.publicLineEdit.setReadOnly(True)
        self.publicLineEdit.setObjectName("publicLineEdit")
        self.algorithmLineEdit = QtWidgets.QLineEdit(ReceiveMessageDialog)
        self.algorithmLineEdit.setGeometry(QtCore.QRect(480, 150, 121, 20))
        self.algorithmLineEdit.setReadOnly(True)
        self.algorithmLineEdit.setObjectName("algorithmLineEdit")
        self.verificationLabel = QtWidgets.QLabel(ReceiveMessageDialog)
        self.verificationLabel.setGeometry(QtCore.QRect(340, 30, 131, 16))
        self.verificationLabel.setObjectName("verificationLabel")
        self.verificationLineEdit = QtWidgets.QLineEdit(ReceiveMessageDialog)
        self.verificationLineEdit.setGeometry(QtCore.QRect(480, 30, 121, 20))
        self.verificationLineEdit.setReadOnly(True)
        self.verificationLineEdit.setObjectName("verificationLineEdit")

        self.retranslateUi(ReceiveMessageDialog)
        self.buttonBox.accepted.connect(ReceiveMessageDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(ReceiveMessageDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(ReceiveMessageDialog)

    def retranslateUi(self, ReceiveMessageDialog):
        _translate = QtCore.QCoreApplication.translate
        ReceiveMessageDialog.setWindowTitle(_translate("ReceiveMessageDialog", "Receive Message"))
        self.compressedCheckBox.setText(_translate("ReceiveMessageDialog", "Compressed"))
        self.encryptedCheckBox.setText(_translate("ReceiveMessageDialog", "Encrypted"))
        self.signedCheckBox.setText(_translate("ReceiveMessageDialog", "Signed"))
        self.publicLabel.setText(_translate("ReceiveMessageDialog", "Public key for encryption:"))
        self.algorithmLabel.setText(_translate("ReceiveMessageDialog", "Encryption algorithm:"))
        self.convertedCheckBox.setText(_translate("ReceiveMessageDialog", "Radix-64 Converted"))
        self.privateLabel.setText(_translate("ReceiveMessageDialog", "Private key for signing:"))
        self.messageLabel.setText(_translate("ReceiveMessageDialog", "Message:"))
        self.verificationLabel.setText(_translate("ReceiveMessageDialog", "Verification:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ReceiveMessageDialog = QtWidgets.QDialog()
    ui = Ui_ReceiveMessageDialog()
    ui.setupUi(ReceiveMessageDialog)
    ReceiveMessageDialog.show()
    sys.exit(app.exec_())
