# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui/send_message.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SendMessageDialog(object):
    def setupUi(self, SendMessageDialog):
        SendMessageDialog.setObjectName("SendMessageDialog")
        SendMessageDialog.resize(640, 530)
        self.buttonBox = QtWidgets.QDialogButtonBox(SendMessageDialog)
        self.buttonBox.setGeometry(QtCore.QRect(240, 460, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.messageText = QtWidgets.QTextEdit(SendMessageDialog)
        self.messageText.setGeometry(QtCore.QRect(40, 200, 561, 231))
        self.messageText.setObjectName("messageText")
        self.messageLabel = QtWidgets.QLabel(SendMessageDialog)
        self.messageLabel.setGeometry(QtCore.QRect(50, 160, 61, 16))
        self.messageLabel.setObjectName("messageLabel")
        self.encryptionCheckBox = QtWidgets.QCheckBox(SendMessageDialog)
        self.encryptionCheckBox.setGeometry(QtCore.QRect(40, 30, 70, 17))
        self.encryptionCheckBox.setObjectName("encryptionCheckBox")
        self.signCheckBox = QtWidgets.QCheckBox(SendMessageDialog)
        self.signCheckBox.setGeometry(QtCore.QRect(40, 60, 70, 17))
        self.signCheckBox.setObjectName("signCheckBox")
        self.compressCheckBox = QtWidgets.QCheckBox(SendMessageDialog)
        self.compressCheckBox.setGeometry(QtCore.QRect(40, 90, 70, 17))
        self.compressCheckBox.setObjectName("compressCheckBox")
        self.convertCheckBox = QtWidgets.QCheckBox(SendMessageDialog)
        self.convertCheckBox.setGeometry(QtCore.QRect(40, 120, 121, 17))
        self.convertCheckBox.setObjectName("convertCheckBox")
        self.privateComboBox = QtWidgets.QComboBox(SendMessageDialog)
        self.privateComboBox.setGeometry(QtCore.QRect(440, 30, 121, 22))
        self.privateComboBox.setObjectName("privateComboBox")
        self.privateLabel = QtWidgets.QLabel(SendMessageDialog)
        self.privateLabel.setGeometry(QtCore.QRect(300, 30, 131, 16))
        self.privateLabel.setObjectName("privateLabel")
        self.publicLabel = QtWidgets.QLabel(SendMessageDialog)
        self.publicLabel.setGeometry(QtCore.QRect(300, 70, 131, 16))
        self.publicLabel.setObjectName("publicLabel")
        self.publicComboBox = QtWidgets.QComboBox(SendMessageDialog)
        self.publicComboBox.setGeometry(QtCore.QRect(440, 70, 121, 22))
        self.publicComboBox.setObjectName("publicComboBox")
        self.algorithmLabel = QtWidgets.QLabel(SendMessageDialog)
        self.algorithmLabel.setGeometry(QtCore.QRect(300, 110, 131, 16))
        self.algorithmLabel.setObjectName("algorithmLabel")
        self.algorithmComboBox = QtWidgets.QComboBox(SendMessageDialog)
        self.algorithmComboBox.setGeometry(QtCore.QRect(440, 110, 121, 22))
        self.algorithmComboBox.setObjectName("algorithmComboBox")
        self.algorithmComboBox.addItem("")
        self.algorithmComboBox.addItem("")

        self.retranslateUi(SendMessageDialog)
        self.buttonBox.accepted.connect(SendMessageDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(SendMessageDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(SendMessageDialog)

    def retranslateUi(self, SendMessageDialog):
        _translate = QtCore.QCoreApplication.translate
        SendMessageDialog.setWindowTitle(_translate("SendMessageDialog", "Send message"))
        self.messageLabel.setText(_translate("SendMessageDialog", "Message:"))
        self.encryptionCheckBox.setText(_translate("SendMessageDialog", "Encryption"))
        self.signCheckBox.setText(_translate("SendMessageDialog", "Sign"))
        self.compressCheckBox.setText(_translate("SendMessageDialog", "Compress"))
        self.convertCheckBox.setText(_translate("SendMessageDialog", "Radix-64 Convert"))
        self.privateLabel.setText(_translate("SendMessageDialog", "Private key for signing:"))
        self.publicLabel.setText(_translate("SendMessageDialog", "Public key for encryption:"))
        self.algorithmLabel.setText(_translate("SendMessageDialog", "Encryption algorithm:"))
        self.algorithmComboBox.setItemText(0, _translate("SendMessageDialog", "Triple DES"))
        self.algorithmComboBox.setItemText(1, _translate("SendMessageDialog", "AES-128"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SendMessageDialog = QtWidgets.QDialog()
    ui = Ui_SendMessageDialog()
    ui.setupUi(SendMessageDialog)
    SendMessageDialog.show()
    sys.exit(app.exec_())
